module.exports.config = {
  name: "loli",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Teri",
  description: "Random ảnh r18 Loli",
  commandCategory: "random-img",
  usages: "loli",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
                    "https://i.imgur.com/E3v72XS.jpeg",
                    "https://i.imgur.com/llRjeS9.jpeg",
                    "https://i.imgur.com/JQm4p1d.jpeg",
                    "https://i.imgur.com/D2xh7qk.jpeg",
                    "https://i.imgur.com/tfBSneJ.jpeg",
                    "https://i.imgur.com/A6XIGl8.jpeg",
                    "https://i.imgur.com/xVvFCAC.jpeg",
                    "https://i.imgur.com/3aZEGeG.jpeg",
                    "https://i.imgur.com/IfMKNpm.jpeg",
                    "https://i.imgur.com/PzTD9CU.jpeg",
                    "https://i.imgur.com/r7yvQGa.jpeg",
                    "https://i.imgur.com/4IWLhs8.jpeg",
                    "https://i.imgur.com/treHs3X.jpeg",
                    "https://i.imgur.com/BiGZIe3.jpeg",
                    "https://i.imgur.com/GIvsCiz.jpeg",
                    "https://i.imgur.com/5o2DVug.jpeg",
                    "https://i.imgur.com/iM1anh3.jpeg",
                    "https://i.imgur.com/dKT9suP.jpeg",
                    "https://i.imgur.com/gFjMTuh.jpeg",
                    "https://i.imgur.com/knBUsAi.jpeg",
                    "https://i.imgur.com/ptNKxWz.jpeg",
                    "https://i.imgur.com/DmBmy7a.jpeg",
                    "https://i.imgur.com/XYsbtKA.jpeg",
                    "https://i.imgur.com/IVZK67K.jpeg",
                    "https://i.imgur.com/4gZuO7W.jpeg",
                    "https://i.imgur.com/XpnYCqZ.jpeg",
                    "https://i.imgur.com/lTj6CVa.jpeg",
                    "https://i.imgur.com/QJsg4Kq.jpeg",
                    "https://i.imgur.com/Rkf06ye.jpeg",
                    "https://i.imgur.com/Ig2eaK2.jpeg",
                    "https://i.imgur.com/N7YYdcL.jpeg",
                    "https://i.imgur.com/nd9XXH7.jpeg",
                    "https://i.imgur.com/Uh5cH4U.jpeg",
                    "https://i.imgur.com/gW84WUV.jpeg",
                    "https://i.imgur.com/cnqTlvY.jpeg",
                    "https://i.imgur.com/SYgKAVt.jpeg",
                    "https://i.imgur.com/VyDV1gH.jpeg",
                    "https://i.imgur.com/OAfP8W8.jpeg",
                    "https://i.imgur.com/bAv5Ls5.jpeg",
                    "https://i.imgur.com/NQqZ9lj.jpeg",
                    "https://i.imgur.com/n7sPhKe.jpeg",
                    "https://i.imgur.com/HzPw4lw.jpeg",
                    "https://i.imgur.com/PjrNRiI.jpeg",
                    "https://i.imgur.com/91E3RRx.jpeg",
                    "https://i.imgur.com/f58hfZP.jpeg",
                    "https://i.imgur.com/LnRuVAM.jpeg",
                    "https://i.imgur.com/uwr0h3P.jpeg",
                    "https://i.imgur.com/r8MHjni.jpeg",
                    "https://i.imgur.com/yKIfso8.jpeg",
                    "https://i.imgur.com/qlVXGDG.jpeg",
                    "https://i.imgur.com/7UUxAmN.jpeg",
                    "https://i.imgur.com/pXRiON2.jpeg",
                    "https://i.imgur.com/MnkEchH.jpeg",
                    "https://i.imgur.com/sBetLrn.jpeg",
                    "https://i.imgur.com/rpvDOGI.jpeg",
                    "https://i.imgur.com/9B6I2QF.jpeg",
                    "https://i.imgur.com/NrjH4yS.jpeg",
                    "https://i.imgur.com/z0NIejM.jpeg",
                    "https://i.imgur.com/vsaCbcY.jpeg",
                    "https://i.imgur.com/JOoNHy6.jpeg",
                    "https://i.imgur.com/cdUr20D.jpeg",
                    "https://i.imgur.com/CKgdday.jpeg",
                    "https://i.imgur.com/Qh6AvAf.jpeg",
                    "https://i.imgur.com/EcR8knC.jpeg",
                    "https://i.imgur.com/wyb8LqL.jpeg",
                    "https://i.imgur.com/bM4bVTg.jpeg",
                    "https://i.imgur.com/K2aCUfz.jpeg",
                    "https://i.imgur.com/SIy1NOy.jpeg",
                    "https://i.imgur.com/yhvAAiC.jpeg",
                    "https://i.imgur.com/QscrQIf.jpeg",
                    "https://i.imgur.com/ZyyHO21.jpeg",
                    "https://i.imgur.com/H5NdbmB.jpeg",
                    "https://i.imgur.com/ac5JcJU.jpeg",
                    "https://i.imgur.com/H0FujJ0.jpeg",
                    "https://i.imgur.com/mtZhHaQ.jpeg",
                    "https://i.imgur.com/yZ8w7j6.jpeg",
                    "https://i.imgur.com/S0Aji4A.jpeg",
                    "https://i.imgur.com/5i2FheL.jpeg",
                    "https://i.imgur.com/MFDcM5K.jpeg",
                    "https://i.imgur.com/NL3OZnw.jpeg",
                    "https://i.imgur.com/cYDBMMd.jpeg",
                    "https://i.imgur.com/zzvG2t5.jpeg",
                    "https://i.imgur.com/gFZ1Wlo.jpeg",
                    "https://i.imgur.com/YbHwt1J.jpeg",
                    "https://i.imgur.com/sgEPCDF.jpeg",
                    "https://i.imgur.com/uc937Tj.jpeg",
                    "https://i.imgur.com/P3ViKKq.jpeg",
                    "https://i.imgur.com/9b7XkXN.jpeg",
                    "https://i.imgur.com/CS7LSP7.jpeg",
                    "https://i.imgur.com/QOqpHqi.jpeg",
                    "https://i.imgur.com/vjZQ6C1.jpeg",
                    "https://i.imgur.com/s70Okgx.jpeg",
                    "https://i.imgur.com/JMCmT3o.jpeg",
                    "https://i.imgur.com/nK8qTvw.jpeg",
                    "https://i.imgur.com/d9BERcg.jpeg",
                    "https://i.imgur.com/tAPkqbb.jpeg",
                    "https://i.imgur.com/8btv9rQ.jpeg",
                    "https://i.imgur.com/1Q13j1v.jpeg",
                    "https://i.imgur.com/He2Fd0r.jpeg",
                    "https://i.imgur.com/3SA83C3.jpeg",
                    "https://i.imgur.com/KCpaqWy.jpeg",
                    "https://i.imgur.com/VGubLCW.jpeg",
                    "https://i.imgur.com/1vgsDkD.jpeg",
                    "https://i.imgur.com/RrPN51N.jpeg",
                    "https://i.imgur.com/ERgW7Ce.jpeg",
                    "https://i.imgur.com/EdXLZak.jpeg",
                    "https://i.imgur.com/2s8fILR.jpeg",
                    "https://i.imgur.com/1dvifVB.jpeg",
                    "https://i.imgur.com/8uRFD2f.jpeg",
                    "https://i.imgur.com/dwRet0R.jpeg",
                    "https://i.imgur.com/w7Xp9b0.jpeg",
                    "https://i.imgur.com/YRK155t.jpeg",
                    "https://i.imgur.com/csyalNQ.jpeg",
                    "https://i.imgur.com/xXdku8O.jpeg",
                    "https://i.imgur.com/cv9LJDi.jpeg",
                    "https://i.imgur.com/0RG6hdx.jpeg",
                    "https://i.imgur.com/HfnWm5s.jpeg",
                    "https://i.imgur.com/g0UoPwg.jpeg",
                    "https://i.imgur.com/8pJsEwg.jpeg",
                    "https://i.imgur.com/InG6Qpt.jpeg",
                    "https://i.imgur.com/p1nCnFw.jpeg",
                    "https://i.imgur.com/KE85HHn.jpeg",
                    "https://i.imgur.com/7MgHpD5.jpeg",
                    "https://i.imgur.com/qr2pOl9.jpeg",
                    "https://i.imgur.com/CL40V4v.jpeg",
                    "https://i.imgur.com/ZFunwYy.jpeg",
                    "https://i.imgur.com/BTiwtsm.jpeg",
                    "https://i.imgur.com/7zuYwpz.jpeg",
                    "https://i.imgur.com/PLzG4uu.jpeg",
                    "https://i.imgur.com/Q5hVKjo.jpeg",
                    "https://i.imgur.com/nChL6F5.jpeg",
                    "https://i.imgur.com/jnTIk9Y.jpeg",
                    "https://i.imgur.com/qtwf2I2.jpeg",
                    "https://i.imgur.com/pFcOENX.jpeg",
                    "https://i.imgur.com/mi33YJC.jpeg",
                    "https://i.imgur.com/QGpTB4z.jpeg",
                    "https://i.imgur.com/6AHXrBd.jpeg",
                    "https://i.imgur.com/fyiM2Et.jpeg",
                    "https://i.imgur.com/F7JNMEU.jpeg",
                    "https://i.imgur.com/6ZvwVwV.jpeg",
                    "https://i.imgur.com/AiHkIKA.jpeg",
                    "https://i.imgur.com/azxj8C4.jpeg",
                    "https://i.imgur.com/nPR4WSi.jpeg",
                    "https://i.imgur.com/YzqNEgm.jpeg",
                    "https://i.imgur.com/yJN4RrP.jpeg",
                    "https://i.imgur.com/UYwacQf.jpeg",
                    "https://i.imgur.com/LbZlSzc.jpeg",
                    "https://i.imgur.com/rXZlVqX.jpeg",
                    "https://i.imgur.com/7m5Vbow.jpeg",
                    "https://i.imgur.com/PvvatTo.jpeg",
                    "https://i.imgur.com/Kb6nvie.jpeg",
                    "https://i.imgur.com/8SLTNGx.jpeg",
                    "https://i.imgur.com/kasHFgq.jpeg",
                    "https://i.imgur.com/ER1bao4.jpeg",
                    "https://i.imgur.com/UDEZ6SW.jpeg",
                    "https://i.imgur.com/M64czgH.jpeg",
                    "https://i.imgur.com/HJIUlT4.jpeg",
                    "https://i.imgur.com/BPHi7Y8.jpeg",
                    "https://i.imgur.com/i3mkAAu.jpeg",
                    "https://i.imgur.com/kSFD4GK.jpeg",
                    "https://i.imgur.com/bmiCds3.jpeg",
                    "https://i.imgur.com/gHLVjaE.jpeg",
                    "https://i.imgur.com/q8Wp3zH.jpeg",
                    "https://i.imgur.com/O5ZlEWA.jpeg",
                    "https://i.imgur.com/NAHJMoH.jpeg",
                    "https://i.imgur.com/2f8yrPi.jpeg",
                    "https://i.imgur.com/NBvMecW.jpeg",
                    "https://i.imgur.com/QAzG8GU.jpeg",
                    "https://i.imgur.com/PxleqCm.jpeg",
                    "https://i.imgur.com/2rYDRPT.jpeg",
                    "https://i.imgur.com/aSp5H4u.jpeg",
                    "https://i.imgur.com/YlsWQMC.jpeg",
                    "https://i.imgur.com/leie6I1.jpeg",
                    "https://i.imgur.com/EV3jKCG.jpeg",
                    "https://i.imgur.com/4azV0BX.jpeg",
                    "https://i.imgur.com/ziXWcdF.jpeg",
                     "https://i.imgur.com/6xVFelQ.jpeg",
                    "https://i.imgur.com/jCPhS5x.jpeg",
                    "https://i.imgur.com/oalyRAL.jpeg",
                    "https://i.imgur.com/2J6lAg4.jpeg",
                    "https://i.imgur.com/TYVZLNo.jpeg",
                    "https://i.imgur.com/A2KSGV0.jpeg",
                    "https://i.imgur.com/l96C75v.jpeg",
                    "https://i.imgur.com/3Bump4c.jpeg",
                    "https://i.imgur.com/xR4KIAV.jpeg",
                    "https://i.imgur.com/toSF3JD.jpeg",
                    "https://i.imgur.com/fmvkK98.jpeg",
                    "https://i.imgur.com/TG1H9Ma.jpeg",
                    "https://i.imgur.com/Q62sigr.jpeg",
                    "https://i.imgur.com/YU4Z5Nn.jpeg",
                    "https://i.imgur.com/Wd6jSr9.jpeg",
                    "ttps://i.imgur.com/JSfMizK.jpeg",
                    "https://i.imgur.com/ZP1qQ3D.jpeg",
                    "https://i.imgur.com/klP6Eo5.jpeg",
                     "https://i.imgur.com/mBiZwWm.jpeg",
                    "https://i.imgur.com/XaRBkat.jpeg",
                    "https://i.imgur.com/cTt8NMa.jpeg",
                    "https://i.imgur.com/1GtuRYF.jpeg",
                    "https://i.imgur.com/BTbeoU5.jpeg",
                    "https://i.imgur.com/MalZFtc.jpeg",
                    "https://i.imgur.com/TVeAn2v.jpeg",
                    "https://i.imgur.com/5LCBJRU.jpeg",
                    "https://i.imgur.com/kpzZYxX.jpeg",
                    "https://i.imgur.com/V26qpC8.jpeg",
                    "https://i.imgur.com/WTirbfk.jpeg",
                    "https://i.imgur.com/fBMoVLb.jpeg",
                    "https://i.imgur.com/KjTQ8hD.jpeg",
                    "https://i.imgur.com/xXDpDi4.jpeg",
                    "https://i.imgur.com/i7WACSy.jpeg",
                    "https://i.imgur.com/06DFEpn.jpeg",
                    "https://i.imgur.com/HKzrbWk.jpeg",
                    "rhttps://i.imgur.com/0QxhJbV.jpeg",
                    "https://i.imgur.com/9YlHiSS.jpeg",
                    "https://i.imgur.com/KEZ8EJ7.jpeg",
                    "https://i.imgur.com/XyjCtSK.jpeg",
                    "https://i.imgur.com/UmDPQmy.jpeg",
                    "https://i.imgur.com/UkyilcD.jpeg",
                    "https://i.imgur.com/zmt9GKd.jpeg",
                    "https://i.imgur.com/kBL2Nzp.jpeg",
                    "https://i.imgur.com/6AikqjG.jpeg",
                    "https://i.imgur.com/7oWLF5f.jpeg",
                    "https://i.imgur.com/lbYVGAD.jpeg",
                    "https://i.imgur.com/bUE6Qbd.jpeg",
                    "https://i.imgur.com/bSpq1B5.jpeg",
                    "https://i.imgur.com/bWETUjn.jpeg",
                    "https://i.imgur.com/qr2ANvB.jpeg",
                    "https://i.imgur.com/uQxMhRK.jpeg",
                    "https://i.imgur.com/mEyWMYT.jpeg",
                    "https://i.imgur.com/iHIgY4K.jpeg",
                    "https://i.imgur.com/MDAA9NJ.jpeg",
                    "https://i.imgur.com/Aoki140.jpeg",
                    "https://i.imgur.com/raJQfa7.jpeg",
                    "https://i.imgur.com/VaUDy7s.jpeg",
                    "https://i.imgur.com/yxyU2IN.jpeg",
                    "https://i.imgur.com/d7qsePi.jpeg",
                    "https://i.imgur.com/GO3br0v.jpeg",
                    "https://i.imgur.com/3rp9eFw.jpeg",
                    "https://i.imgur.com/uiF06F7.jpeg",
                    "https://i.imgur.com/1h00N0u.jpeg",
                    "https://i.imgur.com/gYFEZ68.jpeg",
                    "https://i.imgur.com/Y5FwHCD.jpeg",
                    "https://i.imgur.com/LsalvCV.jpeg ",
                    "https://i.imgur.com/Aue4Ipt.jpeg",
                    "https://i.imgur.com/vpPTpvV.jpeg",
                    "https://i.imgur.com/cdK8TLj.jpeg",
                    "https://i.imgur.com/wJYZUJy.jpeg",
                    "https://i.imgur.com/kOezMLg.jpeg",
                    "https://i.imgur.com/B0DN0mC.jpeg",
    ];
  var max = Math.floor(Math.random() * 6);  
var min = Math.floor(Math.random() * 2);
  var data = await Currencies.getData(event.senderID);
  var exp =  data.exp;
  var money = data.money
      if(money < 1000) api.sendMessage("Bạn cần 1000 đô để xem ảnh ?",event.threadID,event.messageID)
          else {
   Currencies.setData(event.senderID, options = {money: money - 100})
   var callback = () => api.sendMessage({body:`ảnh loli cho ... dm t báo FBI\nSố Ảnh: ${link.length}\n-1000 đô !`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"), event.messageID); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)] + (max - min))).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
     }
   };
 